/*NUMBER GUESSING GAME                                                                                                                                                     Develop the following problem in java language
The fun and easy project "Guess the Number" is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:
1. The system generates a random number from a given range, say 1 to 100. 2. The user is prompted to enter their given number in a displayed dialogue box.
3. The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
4. The game continues under the user guessing the number.
You can also incorporate further details as:
• Limiting the number of attempts.
Adding more rounds.
Displaying score.
• Giving points based on the number of attempts*/

import java.util.Random;
import java.util.Scanner;

public class NumGuesGame{

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        int minRange = 1;
        int maxRange = 100;
        int attempts = 0;
        int score = 0;
        boolean playAgain = true;

        System.out.println("Welcome to the Number Guessing Game!");
        System.out.println("Try to guess the number between " + minRange + " and " + maxRange + ".");

        while (playAgain) {
            int targetNumber = random.nextInt(maxRange - minRange + 1) + minRange;
            int maxAttempts = 10; // You can change the number of attempts allowed

            System.out.println("New round! You have " + maxAttempts + " attempts.");
            attempts = 0;

            while (attempts < maxAttempts) {
                System.out.print("Enter your guess: ");
                int userGuess = scanner.nextInt();
                attempts++;

                if (userGuess == targetNumber) {
                    System.out.println("Congratulations! You guessed the number in " + attempts + " attempts.");
                    score += maxAttempts - attempts + 1; // Calculate the score
                    break;
                } else if (userGuess < targetNumber) {
                    System.out.println("Try a higher number.");
                } else {
                    System.out.println("Try a lower number.");
                }

                if (attempts == maxAttempts) {
                    System.out.println("Out of attempts. The number was " + targetNumber + ".");
                }
            }

            System.out.print("Your score: " + score + ". Play again? (yes/no): ");
            String playAgainInput = scanner.next().toLowerCase();

            if (!playAgainInput.equals("yes")) {
                playAgain = false;
            }
        }

        System.out.println("Thanks for playing! Your final score is: " + score);
        scanner.close();
    }
}
